### ISSUE TITLE
trailing '/' in colcon build --packages-select leads to package is not recognised warning

### ISSUE THREAD

**Issue by daveshed** [colcon/colcon-package-selection#43]
#### Issue description
When I call...
`$ colcon build --packages-select <my_package>/`
I find that I get a warning saying that the package is not recognised and the package is not built. When I remove the trailing slash then all is good and the package builds. Please note that this is unexpected since linux tab-completion will add a trailing slash for a directory.

#### Steps to reproduce the issue

1.  call `$ colcon build --packages-select <my_package>/`
2.  call `$ colcon build --packages-select <my_package>`

#### What's the expected result?

Both calls should be legal and both build the package.

#### What's the actual result?

Call (1) should fail. Call (2) should build

#### Additional details / screenshot

Note that these calls were made on a jetson-tx2 running balena os with a ROS2 eloquent installation.
![image](https://user-images.githubusercontent.com/26175318/97710485-b6023c00-1ab3-11eb-96e9-b2fe873e4f32.png)
Here is some of the output from `python3 -m pip freeze`...
![image](https://user-images.githubusercontent.com/26175318/97710659-f2359c80-1ab3-11eb-9fca-4058d29015df.png)

![image](https://user-images.githubusercontent.com/26175318/97710103-37a59a00-1ab3-11eb-837a-4026b1cfc254.png)

**Comment by dirk-thomas** [comment]
> Both calls should be legal and both build the package.

I have to disagree on that. `<my_package>/` is not a valid package name.

First, you should invoke `colcon build` in the root of the worksapce which is one directory above `src`. Then you won't get the directories within `src` (likely matching your package names with a trailing slash) offered for completion.

Second, if you have `argcomplete` installed and completion for `colcon` enabled (see [docs](https://colcon.readthedocs.io/en/released/user/installation.html#enable-completion)) the possible package names (without a trailing slash) will be offered for completion when you type `colcon build --packages-select <tab>`.

**Comment by daveshed** [comment]
Hi Dirk

Thanks for the prompt reply! Your help is much appreciated.

> First, you should invoke colcon build in the root of the worksapce which is one directory above src. Then you won't get the directories within src (likely matching your package names with a trailing slash) offered for completion.

On this point, it still appears that the trailing slash is inserted for me.

> Second, if you have argcomplete installed and completion for colcon enabled (see docs) the possible package names (without a trailing slash) will be offered for completion when you type colcon build --packages-select <tab>.

It seems that I do indeed have argcomplete installed and sourcing `/usr/share/colcon_argcomplete/hook/colcon_arcomplete.bash` solves this issue.

**Comment by daveshed** [comment]
> I have to disagree on that. <my_package>/ is not a valid package name.

Fair point!
